#!/usr/bin/env node
'use strict';

/**
 * build-studio.js — the plugin's own library, bundled for the browser.
 *
 *   node tools/build-studio.js            → studio/engine.js
 *
 * The studio must draw exactly what `make` builds. A second implementation of
 * the composer in browser code would drift from the first on the first bug fix,
 * so there is none: the same files are wrapped in a tiny module table and given
 * stand-ins for the three Node built-ins they touch.
 *
 * What does not come across: the 170k-word lexicon. It is 0.85 MB and only
 * worth loading for single-edit corrections, so in the browser spelling runs
 * its structural rules alone and `make` does the rest when Claude runs it.
 * The studio says so where it shows spelling notes.
 */

const fs = require('fs');
const path = require('path');

const LIB = path.join(__dirname, '..', 'lib');
const OUT = path.join(__dirname, '..', 'studio', 'engine.js');

const MODULES = [
  'bidi', 'numerals', 'typography', 'detect', 'spelling',
  'patterns', 'compose', 'recipes', 'copy', 'outline', 'cli',
];

function bundle() {
  const table = MODULES.map((name) => {
    const src = fs.readFileSync(path.join(LIB, `${name}.js`), 'utf8')
      .replace(/^#!.*\n/, '');
    return `  './${name}': function (module, exports, require, __filename, __dirname) {\n${src}\n  },`;
  }).join('\n');

  return `/* arabic-design studio engine — generated by tools/build-studio.js, do not edit */
(function () {
  'use strict';
  // Node built-ins the library touches, and what they mean in a browser.
  var Buffer = { byteLength: function (s) { return new TextEncoder().encode(String(s)).length; } };
  var BUILTINS = {
    fs: { existsSync: function () { return false; }, readFileSync: function () { throw new Error('no filesystem in the browser'); } },
    path: { join: function () { return Array.prototype.join.call(arguments, '/'); }, dirname: function (p) { return p; } },
    zlib: {},
  };
  var SOURCES = {
${table}
  };
  var cache = {};
  function load(name) {
    if (BUILTINS[name]) return BUILTINS[name];
    var key = './' + name.replace(/^\\.\\//, '').replace(/\\.js$/, '');
    if (cache[key]) return cache[key].exports;
    if (!SOURCES[key]) throw new Error('studio engine: no module ' + name);
    var module = { exports: {} };
    cache[key] = module;
    var local = function (n) { return load(n); };
    local.main = null;                    // cli.js must not run its main()
    SOURCES[key].call(module.exports, module, module.exports, local, 'lib' + key.slice(1) + '.js', 'lib');
    return module.exports;
  }
  var cli = load('./cli');
  var outline = load('./outline');
  var recipes = load('./recipes');
  var copy = load('./copy');
  var bidi = load('./bidi');
  window.ArabicDesign = {
    make: cli.make,
    parseOutline: outline.parseOutline,
    withBreaks: outline.withBreaks,
    caption: copy.caption,
    lintCopy: copy.lintCopy,
    checkSpine: copy.checkSpine,
    escapeControls: bidi.escapeControls,
    stripBidiControls: bidi.stripBidiControls,
    FORMATS: recipes.FORMATS,
    PALETTES: recipes.PALETTES,
    PAIRINGS: recipes.PAIRINGS,
    PATTERNS: recipes.PATTERNS,
    LAYOUTS: Object.keys(recipes.LAYOUTS),
    combinations: recipes.combinations(),
  };
})();
`;
}

function build() {
  const out = bundle();
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  return { bytes: Buffer.byteLength(out), modules: MODULES.length };
}

if (require.main === module) {
  const { bytes, modules } = build();
  process.stderr.write(`build-studio: ${modules} modules → studio/engine.js (${(bytes / 1024).toFixed(0)} KB)\n`);
}

module.exports = { bundle, build, OUT, MODULES };
